# Generated by Django 5.0.6 on 2024-06-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avionid', models.CharField(null=True)),
                ('marque', models.CharField(null=True)),
                ('model', models.CharField(null=True)),
                ('datefabric', models.DateField(null=True)),
                ('datemisens', models.DateField(null=True)),
            ],
        ),
    ]
